Vagrant.configure("2") do |config|
  # Common settings
  config.vm.network "private_network", type: "dhcp"

  machines = {
    "nginx"     => { box: "ubuntu/bionic64", memory: 512, cpus: 1 },
    "tomcat"    => { box: "centos/7",        memory: 512, cpus: 1 },
    "rabbitmq"  => { box: "centos/7",        memory: 512, cpus: 1 },
    "memcached" => { box: "centos/7",        memory: 512, cpus: 1 },
    "mysql"     => { box: "centos/7",        memory: 512, cpus: 1 },
  }

  machines.each do |name, config_data|
    config.vm.define name do |vm_config|
      vm_config.vm.box = config_data[:box]
      vm_config.vm.hostname = name

      # Проброс портов для каждой машины
      case name
      when "tomcat"
        vm_config.vm.network "forwarded_port", guest: 8080, host: 8080
      when "nginx"
        vm_config.vm.network "forwarded_port", guest: 80, host: 8081
      when "rabbitmq"
        vm_config.vm.network "forwarded_port", guest: 5672, host: 5672
        vm_config.vm.network "forwarded_port", guest: 15672, host: 15672
      when "mysql"
        vm_config.vm.network "forwarded_port", guest: 3306, host: 3306
      when "memcached"
        vm_config.vm.network "forwarded_port", guest: 11211, host: 11211
      end

      vm_config.vm.provider "virtualbox" do |vb|
        vb.memory = config_data[:memory]
        vb.cpus = config_data[:cpus]
      end
    end
  end
end

