---
- name: Deploy Java app to Tomcat server
  hosts: tomcat
  become: yes
  vars:
    aws_region: "{{ lookup('env', 'AWS_REGION') | default('us-east-1') }}"
    aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

  tasks:
    - name: Set ECR registry
      set_fact:
        ecr_registry: "{{ ecr_repo.split('/')[0] }}"

    - name: Login to AWS ECR
      shell: |
        aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ ecr_registry }}
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        AWS_DEFAULT_REGION: "{{ aws_region }}"
      no_log: true

    - name: Pull Docker image from AWS ECR
      community.docker.docker_image:
        name: "{{ ecr_repo }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Stop and remove old container (if running)
      community.docker.docker_container:
        name: tomcat-app
        state: absent
        force_kill: true
        timeout: 10

    - name: Run new Docker container
      community.docker.docker_container:
        name: tomcat-app
        image: "{{ ecr_repo }}:{{ image_tag }}"
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"
